add_newline = false

[directory]
use_os_path_sep = false
read_only_style =	"red"
read_only = " "
format = "[$path]($style)[$read_only]($read_only_style) "

[directory.substitutions]
'W:' = 'work'
'P:' = 'personal'
'R:' = 'resources'
'C:' = 'system-drive'